# Generated by Django 2.2.dev20181228003414 on 2019-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='numpages',
            field=models.CharField(default='', max_length=20),
        ),
    ]
