# Generated by Django 2.2.dev20181228003414 on 2019-01-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0003_auto_20190123_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='open_books',
            field=models.FileField(blank=True, upload_to='pdfs'),
        ),
        migrations.AlterField(
            model_name='book',
            name='books_download',
            field=models.FileField(blank=True, upload_to='books_dataset'),
        ),
    ]
