# Generated by Django 2.2.dev20181228003414 on 2019-01-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0005_auto_20190125_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_pdf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='open_books',
        ),
    ]
