# Generated by Django 2.2.dev20181228003414 on 2019-01-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0006_auto_20190126_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
