# Generated by Django 2.2.dev20181228003414 on 2019-01-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0008_book_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_pdf',
        ),
    ]
