# Generated by Django 2.2.dev20181228003414 on 2019-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0011_remove_book_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, upload_to='book_pdf'),
        ),
    ]
