from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.db.models import Q

from .models import Page, Book

# Create your views here.

def index(request):
    context = {}
    return render(request, 'searchengine/index.html', context)

def search(request):

    def _get_query_set(q: str):
        """Generates the Q model from the query given

        Returns the ``django.db.models.Q`` object.
        the Q object is generated by using OR on space seperated
        keywords of query
        TODO: add the functionality for AND, NOT in Q objects
        """

        q = q.split(' ')
        ret = Q()
        for i in q:
            ret = ret | Q(content__search=i)
        return ret
    q = request.GET.get('q',None)
    if not q:
        return redirect('searchengine:index')
    context = {}
    context['q'] = q
    q = q.strip()
    results = Page.objects.filter(_get_query_set(q))
    context['nresults'] = results.count()
    context['results'] = results
    return render(request, 'searchengine/search.html', context)

def ajax_search(request):

    def _get_query_set(q: str):
        """Generates the Q model from the query given

        Returns the ``django.db.models.Q`` object.
        the Q object is generated by using OR on space seperated
        keywords of query
        TODO: add the functionality for AND, NOT in Q objects
        """

        q = q.split(' ')
        ret = Q()
        for i in q:
            ret = ret | Q(content__search=i)
        return ret

    query = request.GET.get('q',None)
    data = {'results': [], 'error_message':'', 'nresults':0}
    if query is None:
        data['error_message'] = 'No Search Query Given'
        return JsonResponse(data)
    else:
        query = query.strip()
    print('Page database is searching against query: "{}"'.format(query))

    results = Page.objects.filter(_get_query_set(query))
    data['nresults'] = results.count()
    if data['nresults'] == 0:
        data['error_message'] = 'No results found, Please redefine your Search'
        return JsonResponse(data)
    for i in results:
        data['results'].append( {
            'pageid': i.id,
            'pagetitle': i.pagetitle,
            'book': i.book.title,
        })
    return JsonResponse(data)
